#!/usr/bin/env ts-node
/**
 * Discover Application Inference Profiles and Generate CDK Configuration
 *
 * This script discovers all application inference profiles in your AWS account,
 * maps them to their corresponding system inference profiles, and generates
 * TypeScript configuration that can be added to the CDK dashboard stack.
 *
 * Usage:
 *   npx ts-node scripts/discover-inference-profiles.ts [region]
 *
 * Examples:
 *   npx ts-node scripts/discover-inference-profiles.ts
 *   npx ts-node scripts/discover-inference-profiles.ts us-west-2
 */

import {
  BedrockClient,
  ListInferenceProfilesCommand,
  InferenceProfileSummary,
  InferenceProfileModel,
} from '@aws-sdk/client-bedrock';

interface ProfileGroup {
  systemProfileId: string;
  applicationProfiles: Array<{
    id: string;
    name: string;
  }>;
}

/**
 * Fetch inference profiles of a specific type from Bedrock
 */
async function getInferenceProfilesByType(
  client: BedrockClient,
  profileType: 'SYSTEM_DEFINED' | 'APPLICATION'
): Promise<InferenceProfileSummary[]> {
  const profiles: InferenceProfileSummary[] = [];
  let nextToken: string | undefined;

  do {
    const response = await client.send(
      new ListInferenceProfilesCommand({
        typeEquals: profileType,
        nextToken,
        maxResults: 100,
      })
    );

    if (response.inferenceProfileSummaries) {
      profiles.push(...response.inferenceProfileSummaries);
    }
    nextToken = response.nextToken;
  } while (nextToken);

  return profiles;
}

/**
 * Extract the model ID from a foundation model ARN
 * Example: arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-sonnet-4-5-20250929-v1:0
 * Returns: anthropic.claude-sonnet-4-5-20250929-v1:0
 */
function extractModelIdFromFoundationArn(arn: string): string | null {
  const match = arn.match(/foundation-model\/(.+)$/);
  return match ? match[1] : null;
}

/**
 * Get the set of foundation model IDs from a profile's models array
 */
function getFoundationModelIds(models: InferenceProfileModel[] | undefined): Set<string> {
  const modelIds = new Set<string>();
  if (!models) return modelIds;

  for (const model of models) {
    if (model.modelArn) {
      const modelId = extractModelIdFromFoundationArn(model.modelArn);
      if (modelId) {
        modelIds.add(modelId);
      }
    }
  }
  return modelIds;
}

/**
 * Determine which system inference profile an application profile corresponds to
 * by comparing the foundation models they route to
 */
function determineSystemProfileId(
  appProfile: InferenceProfileSummary,
  systemProfiles: InferenceProfileSummary[]
): string | null {
  const appModelIds = getFoundationModelIds(appProfile.models);
  if (appModelIds.size === 0) return null;

  for (const sysProfile of systemProfiles) {
    const sysModelIds = getFoundationModelIds(sysProfile.models);

    // Check if the foundation models match exactly
    if (
      appModelIds.size === sysModelIds.size &&
      [...appModelIds].every((id) => sysModelIds.has(id))
    ) {
      return sysProfile.inferenceProfileId || null;
    }
  }

  return null;
}

/**
 * Build groups of profiles that share the same quota
 */
function buildProfileGroups(
  appProfiles: InferenceProfileSummary[],
  systemProfiles: InferenceProfileSummary[]
): Map<string, ProfileGroup> {
  const groups = new Map<string, ProfileGroup>();

  for (const profile of appProfiles) {
    const profileId = profile.inferenceProfileId || '';
    const profileName = profile.inferenceProfileName || '';

    const systemProfileId = determineSystemProfileId(profile, systemProfiles);

    if (systemProfileId) {
      if (!groups.has(systemProfileId)) {
        groups.set(systemProfileId, {
          systemProfileId,
          applicationProfiles: [],
        });
      }

      groups.get(systemProfileId)!.applicationProfiles.push({
        id: profileId,
        name: profileName,
      });
    }
  }

  return groups;
}

/**
 * Generate TypeScript configuration for the CDK stack
 */
function generateTypeScriptConfig(groups: Map<string, ProfileGroup>): string {
  const lines: string[] = [];
  lines.push('// Application Inference Profile Configuration');
  lines.push('// Generated by: npx ts-node scripts/discover-inference-profiles.ts');
  lines.push('// Add these to your DashboardConfig in lib/cdk-quota-dashboards-stack.ts');
  lines.push('');
  lines.push('// Example usage in allDashboardConfigs:');
  lines.push('// {');
  lines.push('//   modelConfig: BEDROCK_MODELS.ANTHROPIC.CLAUDE_SONNET_4_5,');
  lines.push("//   endpointType: 'cross-region',");
  lines.push("//   applicationProfileIds: ['profile1', 'profile2'],  // <-- Add this");
  lines.push('// }');
  lines.push('');

  for (const [systemId, group] of groups) {
    if (group.applicationProfiles.length === 0) continue;

    lines.push(`// System Profile: ${systemId}`);
    lines.push('// Application Profiles:');
    for (const app of group.applicationProfiles) {
      lines.push(`//   - ${app.id} (${app.name})`);
    }

    const profileIds = group.applicationProfiles.map((app) => app.id);
    lines.push(`applicationProfileIds: ${JSON.stringify(profileIds)},`);
    lines.push('');
  }

  return lines.join('\n');
}

async function main() {
  const region = process.argv[2] || process.env.AWS_DEFAULT_REGION || 'us-east-1';

  console.log('='.repeat(70));
  console.log('Bedrock Application Inference Profile Discovery');
  console.log(`Region: ${region}`);
  console.log('='.repeat(70));

  const client = new BedrockClient({ region });

  // Fetch profiles
  console.log('\nFetching inference profiles...');
  const systemProfiles = await getInferenceProfilesByType(client, 'SYSTEM_DEFINED');
  const appProfiles = await getInferenceProfilesByType(client, 'APPLICATION');

  console.log(`  Found ${systemProfiles.length} system profiles`);
  console.log(`  Found ${appProfiles.length} application profiles`);

  if (appProfiles.length === 0) {
    console.log('\nNo application inference profiles found in this account/region.');
    console.log('Create application profiles using the AWS Console or CLI:');
    console.log('  aws bedrock create-inference-profile \\');
    console.log("    --inference-profile-name 'my-profile' \\");
    console.log(
      '    --model-source \'{"copyFrom": "arn:aws:bedrock:us-east-1:ACCOUNT:inference-profile/us.anthropic.claude-sonnet-4-5-20250929-v1:0"}\''
    );
    return;
  }

  // Build groups
  const groups = buildProfileGroups(appProfiles, systemProfiles);
  const groupsWithProfiles = new Map(
    [...groups].filter(([, v]) => v.applicationProfiles.length > 0)
  );

  // Display results
  console.log('\n' + '-'.repeat(70));
  console.log('Profile Groups (System Profile -> Application Profiles)');
  console.log('-'.repeat(70));

  for (const [systemId, group] of groupsWithProfiles) {
    const appCount = group.applicationProfiles.length;
    console.log(`\n${systemId}`);
    console.log(`  Application profiles (${appCount}):`);
    for (const app of group.applicationProfiles) {
      console.log(`    - ${app.id}: ${app.name}`);
    }
  }

  // Generate TypeScript config
  console.log('\n' + '='.repeat(70));
  console.log('CDK Configuration (copy to your stack)');
  console.log('='.repeat(70));
  console.log();
  console.log(generateTypeScriptConfig(groupsWithProfiles));

  // Summary
  let totalAppProfiles = 0;
  for (const group of groupsWithProfiles.values()) {
    totalAppProfiles += group.applicationProfiles.length;
  }
  const unmatched = appProfiles.length - totalAppProfiles;

  console.log('-'.repeat(70));
  console.log('Summary');
  console.log('-'.repeat(70));
  console.log(`  System profiles with app profiles: ${groupsWithProfiles.size}`);
  console.log(`  Total application profiles mapped: ${totalAppProfiles}`);
  if (unmatched > 0) {
    console.log(`  Unmatched application profiles: ${unmatched}`);
    console.log('    (These may be regional profiles without cross-region system profiles)');
  }
}

// Show usage if --help is passed
if (process.argv.includes('--help') || process.argv.includes('-h')) {
  console.log('Usage: npx ts-node scripts/discover-inference-profiles.ts [region]');
  console.log('\nDiscovers application inference profiles and generates CDK configuration.');
  console.log('\nOptional region parameter (defaults to us-east-1 or AWS_DEFAULT_REGION)');
  console.log('\nThe output shows which application profiles share quota with system profiles,');
  console.log('and provides configuration to add to your CDK dashboard stack.');
  process.exit(0);
}

main().catch((error) => {
  console.error('Error:', error.message);
  console.log('\nMake sure you have:');
  console.log('1. AWS credentials configured');
  console.log('2. Permissions for bedrock:ListInferenceProfiles');
  console.log('3. Bedrock service available in your region');
  process.exit(1);
});
